object ScanForm: TScanForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'ScanForm'
  ClientHeight = 886
  ClientWidth = 1598
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnKeyDown = FormKeyDown
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 13
end
